#!/usr/bin/env python3
"""Generate the full-colour Game launcher icon from the supplied artwork."""
from pathlib import Path
from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "tools/assets/game-icon-source.png"
C_OUTPUT = ROOT / "lib/meshtastic-device-ui/source/graphics/TFT/GameLauncherIcon.c"
PREVIEWS = (
    ROOT / "simulator/mac-preview/assets/icons/launcher/game.png",
    ROOT / "../../website/tdeck-simulator/assets/icons/launcher/game.png",
)
SIZE = (40, 40)


def rgb565(r, g, b):
    v = ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)
    return bytes((v & 0xFF, v >> 8))


def main():
    image = Image.open(SOURCE).convert("RGBA")
    image = image.crop(image.getchannel("A").getbbox())
    image.thumbnail(SIZE, Image.Resampling.LANCZOS)
    canvas = Image.new("RGBA", SIZE, (0, 0, 0, 0))
    canvas.alpha_composite(image, ((SIZE[0] - image.width) // 2, (SIZE[1] - image.height) // 2))
    for path in PREVIEWS:
        path.parent.mkdir(parents=True, exist_ok=True)
        canvas.save(path, optimize=True)

    data = bytearray()
    for r, g, b, _ in canvas.get_flattened_data():
        data.extend(rgb565(r, g, b))
    data.extend(canvas.getchannel("A").tobytes())
    lines = ['/* Generated by tools/generate_game_icon.py. */', '#include "lvgl.h"', '', 'static const uint8_t img_launcher_game_icon_map[] = {']
    for start in range(0, len(data), 16):
        lines.append("    " + ",".join(f"0x{v:02x}" for v in data[start:start + 16]) + ",")
    lines.extend([
        '};',
        'const lv_image_dsc_t img_launcher_game_icon = {',
        '    .header.magic = LV_IMAGE_HEADER_MAGIC,',
        '    .header.cf = LV_COLOR_FORMAT_RGB565A8,',
        '    .header.flags = 0, .header.w = 40, .header.h = 40, .header.stride = 80,',
        '    .data_size = sizeof(img_launcher_game_icon_map), .data = img_launcher_game_icon_map,',
        '};',
        '',
    ])
    C_OUTPUT.write_text("\n".join(lines))


if __name__ == "__main__":
    main()
