#!/usr/bin/env python3
"""Generate monochrome transparent launcher logos for the web demo and LVGL."""

from pathlib import Path

from PIL import Image, ImageChops, ImageDraw, ImageOps

ROOT = Path(__file__).resolve().parents[1]
ASSET_DIR = ROOT / "simulator/mac-preview/assets/icons"
PREVIEW_DIR = ASSET_DIR / "launcher"
LVGL_DIR = ROOT / "lib/meshtastic-device-ui/generated/ui_320x240"
LOGOS = {
    "mesh": "mesh-logo.png", "notes": "notes-logo.png", "ollama": "ollama-logo.png",
    "calendar": "calendar-logo.png", "terminal": "terminal-logo.png",
    "calculator": "calculator-logo.png", "files": "files-logo.png", "maps": "maps-logo.png",
    "clock": "clock-logo.jpg", "settings": "settings-logo.png",
    "getapps": "apps-wordmark.png", "alerts": "alerts-logo.png",
    "favorites": "favorites-logo.png", "chats": "chats-logo.png",
}


def make_mask(path: Path) -> Image.Image:
    source = Image.open(path).convert("RGBA")
    gray = ImageOps.grayscale(source.convert("RGB"))
    corners = [source.convert("RGB").getpixel(p) for p in ((0, 0), (source.width - 1, 0),
                                                           (0, source.height - 1), (source.width - 1, source.height - 1))]
    luma = sum((r * 30 + g * 59 + b * 11) // 100 for r, g, b in corners) // 4
    mask = ImageOps.invert(gray) if luma >= 128 else gray
    if path.name == "chats-logo.png":
        # The supplied chat mark has a checkerboard baked into its RGB pixels.
        # Keep only dark ink, making the checker pattern transparent.
        mask = ImageOps.invert(gray).point(lambda value: 0 if value < 45 else min(255, (value - 45) * 3))
    mask = ImageChops.multiply(mask, source.getchannel("A"))
    bounds = mask.point(lambda v: 255 if v > 10 else 0).getbbox()
    if not bounds:
        raise ValueError(f"No logo pixels found in {path}")
    mask = mask.crop(bounds)
    mask.thumbnail((36, 36), Image.Resampling.LANCZOS)
    canvas = Image.new("L", (40, 40), 0)
    canvas.paste(mask, ((40 - mask.width) // 2, (40 - mask.height) // 2))
    return canvas


def make_accounts_mask() -> Image.Image:
    """Extract the supplied knot only, dropping the horizontal tails outside it."""
    source = Image.open(ASSET_DIR / "accounts-logo.png").convert("RGB")
    # The knot itself spans the middle; cropping at its outer loops excludes the
    # detached-looking horizontal end bars from the reference image.
    source = source.crop((88, 137, 329, 277))
    mask = ImageOps.invert(ImageOps.grayscale(source))
    mask = mask.point(lambda value: 0 if value < 24 else value)
    mask.thumbnail((38, 36), Image.Resampling.LANCZOS)
    canvas = Image.new("L", (40, 40), 0)
    canvas.paste(mask, ((40 - mask.width) // 2, (40 - mask.height) // 2))
    return canvas


def main() -> None:
    PREVIEW_DIR.mkdir(parents=True, exist_ok=True)
    LVGL_DIR.mkdir(parents=True, exist_ok=True)
    declarations = []
    source = ['/* Generated by tools/generate_launcher_logos.py; do not edit by hand. */', '#include "lvgl.h"', ""]
    for name, filename in LOGOS.items():
        mask = make_mask(ASSET_DIR / filename)
        image = Image.new("RGBA", (40, 40), (255, 255, 255, 0))
        image.putalpha(mask)
        image.save(PREVIEW_DIR / f"{name}.png", optimize=True)
        symbol = f"img_launcher_{name}_logo"
        declarations.append(f"extern const lv_image_dsc_t {symbol};")
        pixels = bytes((0xFF, 0xFF)) * 1600 + mask.tobytes()
        source.append(f"static const uint8_t {symbol}_map[] = {{")
        for start in range(0, len(pixels), 16):
            source.append("    " + ",".join(f"0x{byte:02x}" for byte in pixels[start:start + 16]) + ",")
        source.extend([
            "};", f"const lv_image_dsc_t {symbol} = {{",
            "    .header.magic = LV_IMAGE_HEADER_MAGIC,",
            "    .header.cf = LV_COLOR_FORMAT_RGB565A8,",
            "    .header.flags = 0, .header.w = 40, .header.h = 40, .header.stride = 80,",
            f"    .data_size = sizeof({symbol}_map), .data = {symbol}_map,", "};", "",
        ])
    mask = make_accounts_mask()
    image = Image.new("RGBA", (40, 40), (255, 255, 255, 0))
    image.putalpha(mask)
    image.save(PREVIEW_DIR / "accounts.png", optimize=True)
    symbol = "img_launcher_accounts_logo"
    declarations.append(f"extern const lv_image_dsc_t {symbol};")
    pixels = bytes((0xFF, 0xFF)) * 1600 + mask.tobytes()
    source.append(f"static const uint8_t {symbol}_map[] = {{")
    for start in range(0, len(pixels), 16):
        source.append("    " + ",".join(f"0x{byte:02x}" for byte in pixels[start:start + 16]) + ",")
    source.extend([
        "};", f"const lv_image_dsc_t {symbol} = {{",
        "    .header.magic = LV_IMAGE_HEADER_MAGIC,",
        "    .header.cf = LV_COLOR_FORMAT_RGB565A8,",
        "    .header.flags = 0, .header.w = 40, .header.h = 40, .header.stride = 80,",
        f"    .data_size = sizeof({symbol}_map), .data = {symbol}_map,", "};", "",
    ])
    (LVGL_DIR / "ui_image_launcher_logos.c").write_text("\n".join(source))
    header = LVGL_DIR / "images.h"
    existing = header.read_text()
    marker = "/* Generated launcher logo descriptors. */"
    block = marker + "\n" + "\n".join(declarations) + "\n"
    if marker in existing:
        start = existing.index(marker)
        end = existing.index("\n", existing.index(";", start)) + 1
        while end < len(existing) and existing.startswith("extern const lv_image_dsc_t", end):
            end = existing.index("\n", end) + 1
        existing = existing[:start] + existing[end:]
    anchor = "#ifdef __cplusplus\n}\n#endif"
    if block not in existing:
        existing = existing.replace(anchor, block + "\n" + anchor)
    header.write_text(existing)


if __name__ == "__main__":
    main()
