#!/usr/bin/env python3
"""Convert the supplied map marker PNGs into compact LVGL RGB565A8 assets."""

from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
ASSETS = ROOT / "tools/assets/map-markers"
OUTPUT = ROOT / "lib/meshtastic-device-ui/source/graphics/TFT/MapMarkerImages.c"

MARKERS = (
    ("gps_raven", "gps-raven-source.png", (32, 40)),
    ("feather", "feather-source.png", (32, 32)),
    ("wifi", "wifi-source.png", (32, 32)),
    ("place", "place-source.png", (32, 32)),
    ("mission_flag", "mission-flag-source.png", (32, 32)),
    ("loot_chest", "loot-chest-source.png", (32, 32)),
    ("danger", "danger-source.png", (32, 32)),
    ("water", "water-source.png", (32, 32)),
    ("camp", "camp-source.png", (32, 32)),
    ("mesh_node", "mesh-node-source.png", (32, 32)),
)


def rgb565(r: int, g: int, b: int) -> bytes:
    value = ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)
    return bytes((value & 0xFF, (value >> 8) & 0xFF))


def convert(source: Path, size: tuple[int, int]) -> Image.Image:
    image = Image.open(source).convert("RGBA")
    alpha = image.getchannel("A")
    bounds = alpha.getbbox()
    if not bounds:
        raise ValueError(f"Image has no visible pixels: {source}")
    image = image.crop(bounds)
    image.thumbnail(size, Image.Resampling.NEAREST)
    canvas = Image.new("RGBA", size, (0, 0, 0, 0))
    canvas.alpha_composite(image, ((size[0] - image.width) // 2, (size[1] - image.height) // 2))
    return canvas


def c_bytes(image: Image.Image) -> bytes:
    pixels = bytearray()
    for r, g, b, _ in image.getdata():
        pixels.extend(rgb565(r, g, b))
    pixels.extend(image.getchannel("A").tobytes())
    return bytes(pixels)


def main() -> None:
    lines = ['/* Generated by tools/generate_map_markers.py. */', '#include "lvgl.h"', ""]
    for symbol, filename, size in MARKERS:
        image = convert(ASSETS / filename, size)
        image.save(ASSETS / f"{symbol}-preview.png", optimize=True)
        data = c_bytes(image)
        lines.append(f"static const uint8_t img_map_marker_{symbol}_map[] = {{")
        for start in range(0, len(data), 16):
            row = ",".join(f"0x{value:02x}" for value in data[start : start + 16])
            lines.append(f"    {row},")
        lines.extend(
            [
                "};",
                f"const lv_image_dsc_t img_map_marker_{symbol} = {{",
                "    .header.magic = LV_IMAGE_HEADER_MAGIC,",
                "    .header.cf = LV_COLOR_FORMAT_RGB565A8,",
                "    .header.flags = 0,",
                f"    .header.w = {size[0]}, .header.h = {size[1]}, .header.stride = {size[0] * 2},",
                f"    .data_size = sizeof(img_map_marker_{symbol}_map),",
                f"    .data = img_map_marker_{symbol}_map,",
                "};",
                "",
            ]
        )
    OUTPUT.write_text("\n".join(lines))


if __name__ == "__main__":
    main()
