(() => {
  const KEY = "tdeck-mac-sim-v1";
  const initial = { page: "launcher", launcherPage:0, glass: true, t9: true, menu: false, keyboard: false, zoom: 1, model: "glm-5.3-flash", mode: "Chat", month: 9, year: 2026, day: 5, notes: [], favorites: [], events: [], todos: [], mapPins: [], dayNotes: {}, daySettings: {}, chat: [], terminal: ["Terminal bereit."], termConnected: false, termStatus: "Bereit", termZoom: 0, transitPlan: "sbahn-ubahn", transitZoom: 1, transitX: 0, transitY: 0 };
  let state;
  try { state = { ...initial, ...JSON.parse(localStorage.getItem(KEY) || "{}") }; } catch { state = { ...initial }; }
  const view = document.getElementById("view");
  const statusbar = document.getElementById("statusbar");
  const simState = document.getElementById("simState");
  const deviceKeyboard = document.getElementById("keyboard");
  let activeInput = null;
  let suggestionBar = null;
  let transitDrag = null;
  let toastTimer;
  const apps = [
    ["Meshtastic", "◉", "mesh"], ["Notizen", "▤", "notes"], ["Ollama-Agent", "◉", "ollama"], ["Kalender", "▦", "calendar"],
    ["Terminal", "›_", "terminal"], ["Rechner", "＋", "calculator"], ["Dateien", "▣", "files"], ["Karte", "⌖", "map"],
    ["Einstellungen", "⚙", "settings"], ["Apps holen", "↓", "getapps"], ["Uhr", "◷", "clock"], ["Knoten", "◉", "nodes"],
    ["Favoriten", "☆", "favorites"], ["Chats", "☷", "chats"], ["Meldungen", "!", "alerts"]
  ];
  const transitPlans = [
    ["sbahn-ubahn", "S-/U-Bahn", "sbahn-ubahn.webp"],
    ["tram", "Straßenbahn", "tram.webp"],
    ["bus", "Buslinien", "bus.webp"],
    ["regional", "Regionalverkehr", "regional.webp"],
    ["night", "Nachtnetz", "night.webp"]
  ];
  const t9Words = ["aber","alle","allem","allen","alles","also","am","an","auch","auf","aus","beim","bei","bitte","bis","bist","brauche","danke","das","dass","dein","dem","den","der","des","die","dies","dir","doch","dort","du","durch","ein","eine","einen","einer","es","etwas","für","ganz","gehen","geht","gibt","habe","haben","hat","heute","hier","ich","immer","in","ist","ja","jetzt","kann","keine","kleine","machen","man","mehr","mein","meine","mit","mich","mir","morgen","nach","nicht","noch","nur","oder","ohne","schon","sehr","sein","seine","sich","sie","sind","so","soll","sollte","später","über","um","und","uns","unter","vom","von","vor","war","warum","was","welche","wenn","wer","werden","wie","wieder","will","wir","wird","wo","zu","zum","zur"];
  const esc = s => String(s).replace(/[&<>"']/g, c => ({ "&":"&amp;", "<":"&lt;", ">":"&gt;", '"':"&quot;", "'":"&#39;" }[c]));
  const save = () => { localStorage.setItem(KEY, JSON.stringify({ ...state, menu:false, keyboard:false })); };
  const title = (t, extra="") => `<div class="app-head" data-app-title="${esc(t)}">${extra}<span>${esc(t)}</span><button class="menu-button" data-action="menu" aria-label="Menü">☰</button></div>`;
  const content = html => `<div class="content">${html}</div>`;
  const toast = text => { let old=view.querySelector(".toast"); if(old) old.remove(); const n=document.createElement("div"); n.className="toast"; n.textContent=text; view.append(n); clearTimeout(toastTimer); toastTimer=setTimeout(()=>n.remove(),1900); };
  const saveActiveNote = () => {
    if(state.page!=="notes"||!state.activeNoteId)return;
    const note=state.notes.find(n=>n.id===state.activeNoteId);
    if(!note)return;
    note.title=document.getElementById("noteTitle")?.value??note.title;
    note.body=document.getElementById("noteBody")?.value??note.body;
    note.updatedAt=new Date().toISOString();
  };
  const navigate = page => { saveActiveNote(); if(page!==state.page)state.activeNoteId=null; state.page=page; state.menu=false; state.keyboard=false; render(); save(); };
  const dayKey = (y,m,d) => `${y}-${String(m+1).padStart(2,"0")}-${String(d).padStart(2,"0")}`;
  function menuMarkup() {
    if(!state.menu) return "";
    const common = `<button data-action="keyboard">⌨ Tastatur einblenden</button><button data-action="zoom">⌕ Schriftgröße: ${["Klein","Normal","Groß"][state.zoom??1]}</button><button data-action="close-menu">Schließen</button><button data-action="home">Zur Übersicht</button>`;
    let specific="";
    if(state.page==="ollama") specific = `<button data-action="model">Modell: ${esc(state.model)}</button><button data-action="mode">Modus: ${esc(state.mode==="Markdown"?"Markdown":"Chat")}</button><button data-action="save-chat">Speichern → Notizen</button><button data-action="delete-chat">Chat löschen</button><button data-action="open-calendar">Kalender öffnen</button>`;
    if(state.page==="map") specific = `<button data-action="map-style">Kartenstil: ${esc(state.mapStyle||"OSM-Carto")}</button><button data-action="zoom-map">Zoom ändern (${state.mapZoom||16})</button><button data-action="open-transit">ÖPNV-Netzpläne öffnen</button>`;
    if(state.page==="terminal") return `<div class="menu-pop terminal-menu"><div class="terminal-menu-title">Terminal</div><button class="terminal-connect ${state.termConnected?"connected":""}" data-action="ssh">${state.termConnected?"Trennen":"Verbinden"}</button><button class="terminal-read" data-action="read-terminal">Protokoll lesen</button><button class="terminal-clear" data-action="clear-terminal">Leeren</button><span class="terminal-zoom-label">Schrift</span><button class="terminal-zoom-out" data-action="term-zoom-out">−</button><span class="terminal-zoom-value">${["Klein","Normal","Groß"][state.termZoom||0]}</span><button class="terminal-zoom-in" data-action="term-zoom-in">+</button><button class="terminal-close" data-action="close-menu">Schließen</button><span class="terminal-status">${esc(state.termStatus||"Bereit")}</span></div>`;
    if(state.page==="transit") return `<div class="menu-pop transit-menu"><div class="transit-menu-title">ÖPNV-Netzplan</div><select data-action="transit-select" aria-label="Netzplan auswählen">${transitPlans.map(([id,label])=>`<option value="${id}" ${state.transitPlan===id?"selected":""}>${label}</option>`).join("")}</select><div class="transit-zoom-row"><button data-action="transit-zoom-out" aria-label="Karte verkleinern">−</button><span>${Math.round((state.transitZoom||1)*100)}%</span><button data-action="transit-zoom-in" aria-label="Karte vergrößern">+</button></div><button data-action="transit-center">Plan zentrieren</button><button data-action="transit-osm">Zur OSM-Karte</button><button data-action="close-menu">Schließen</button></div>`;
    if(state.page==="calendar") specific = `<button data-action="today">Zu heute</button><button data-action="save-day">Tag speichern</button><button data-action="new-event">Termin für ${dayKey(state.year,state.month,state.day)}</button>`;
    return `<div class="menu-pop">${specific}${common}</div>`;
  }
  function hideSuggestions(){suggestionBar?.remove();suggestionBar=null;}
  function updateSuggestions(input){
    hideSuggestions();
    if(!state.t9||!input?.isConnected)return;
    const prefix=(input.value.slice(0,input.selectionStart??input.value.length).match(/[A-Za-z]+$/)||[])[0];
    if(!prefix)return;
    const matches=t9Words.filter(word=>word.toLowerCase().startsWith(prefix.toLowerCase())&&word.length>prefix.length).slice(0,3);
    if(!matches.length)return;
    suggestionBar=document.createElement("div");suggestionBar.className="t9-suggestions";suggestionBar.setAttribute("aria-label","T9-Wortvorschläge");
    const viewRect=view.getBoundingClientRect(),inputRect=input.getBoundingClientRect();
    let top=inputRect.top-viewRect.top-30;if(top<0)top=inputRect.bottom-viewRect.top+2;
    suggestionBar.style.top=`${Math.max(0,Math.min(top,view.clientHeight-28))}px`;
    matches.forEach(word=>{const button=document.createElement("button");button.type="button";button.textContent=word;button.addEventListener("mousedown",event=>event.preventDefault());button.addEventListener("click",()=>{const end=input.selectionStart??input.value.length;const left=input.value.slice(0,end).replace(/[A-Za-z]+$/,""),right=input.value.slice(end);input.value=left+word+" "+right;input.setSelectionRange?.((left+word+" ").length,(left+word+" ").length);input.dispatchEvent(new Event("input",{bubbles:true}));input.focus();});suggestionBar.append(button);});
    view.append(suggestionBar);
  }
  function launcher() {
    const page=Math.max(0,Math.min(1,state.launcherPage||0));
    return `<div class="launcher ${state.glass?"glass":""}">${apps.slice(page*12,(page+1)*12).map(([name,glyph,id])=>{const logos={mesh:"mesh.png",notes:"notes.png",ollama:"ollama.png",terminal:"terminal.png",calendar:"calendar.png",files:"files.png",map:"maps.png",calculator:"calculator.png",clock:"clock.png",settings:"settings.png",getapps:"getapps.png",accounts:"accounts.png",nodes:"accounts.png",alerts:"alerts.png",favorites:"favorites.png",chats:"chats.png"};const logo=logos[id]?`assets/icons/launcher/${logos[id]}`:null;return `<button class="app-icon app-${id} ${logo?"image-app":""}" data-open="${id}"><span class="glyph">${logo?`<img src="${logo}" alt="${esc(name)}">`:glyph}</span><small>${esc(name)}</small></button>`;}).join("")}<span class="launcher-page page-${page}" aria-label="Seite ${page+1} von 2"></span><button class="launcher-shortcut shortcut-todo" data-action="quick-todo">TO DO &gt;&gt;</button><button class="launcher-shortcut shortcut-point" data-action="quick-point">POINT &gt;&gt;</button></div>`;
  }
  function mapPage() {
    const style=state.mapStyle||"OSM-Carto";
    const tiles=[["16-35223-21489.png","16-35224-21489.png"],["16-35223-21490.png","16-35224-21490.png"]];
    const pin=state.mapPins?.length?`<span class="map-user-pin" title="${esc(state.mapPins.at(-1).label)}">●<small>${esc(state.mapPins.at(-1).label)}</small></span>`:"";
    return `${title("Meshtastic · Karte")}<div class="mapview"><div class="mapgrid">${tiles.flat().map(f=>`<img src="assets/maps/${f}" alt="Lokale OSM-Carto-Testkachel" draggable="false">`).join("")}</div><span class="mapdot"></span>${pin}<div class="map-label">${esc(style)} · Zoomstufe ${state.mapZoom||16}${style!=="OSM-Carto"?" · Stil-Demo":""}</div><div class="map-footer"><select data-action="map-select" aria-label="Kartenebene"><option ${style==="OSM-Carto"?"selected":""}>OSM-Carto</option><option ${style==="Tram"?"selected":""}>Straßenbahn</option><option ${style==="S-Bahn"?"selected":""}>S-Bahn</option><option ${style==="U-Bahn"?"selected":""}>U-Bahn</option><option ${style==="WLAN"?"selected":""}>WLAN</option></select><button class="small-btn" data-action="zoom-map" aria-label="Zoom ändern">− / +</button><button class="small-btn map-transit-button" data-action="open-transit">Linienpläne</button></div></div>${menuMarkup()}`;
  }
  function todoPage(){const rows=(state.todos||[]).map((task,index)=>`<div class="todo-row ${task.done?"done":""}"><button class="todo-check" data-todo-toggle="${index}" aria-label="Aufgabe erledigen">${task.done?"✓":"○"}</button><span>${esc(task.text)}</span><button class="todo-delete" data-todo-delete="${index}" aria-label="Aufgabe löschen">×</button></div>`).join("");return `${title("To-do-Liste")}<form class="todo-form" id="todoForm"><input id="todoInput" maxlength="80" placeholder="Aufgabe eingeben…" autocomplete="off"><button class="blue-btn" type="submit">＋</button></form><div class="todo-list">${rows||`<div class="muted todo-empty">Noch keine Aufgaben. Schreib oben deine erste To-do.</div>`}</div>${menuMarkup()}`;}
  function transitPage() {
    const plan=transitPlans.find(([id])=>id===state.transitPlan)||transitPlans[0];
    const scale=state.transitZoom||1, x=state.transitX||0, y=state.transitY||0;
    return `${title(`ÖPNV · ${plan[1]}`)}<div class="transit-viewport"><img class="transit-map-image" src="assets/transit/${plan[2]}" alt="${esc(plan[1])} Berlin/Brandenburg, Offline-Netzplan" draggable="false" style="transform:translate(calc(-50% + ${x}px),calc(-50% + ${y}px)) scale(${scale})"><span class="transit-offline-badge">${esc(plan[1])} · offline</span><span class="transit-gesture-hint">Menü: Plan · Zoom</span></div>${menuMarkup()}`;
  }
  function chatPage() {
    const bubbles=state.chat.map(x=>`<div class="bubble ${x.role==="user"?"user":"bot"}">${esc(x.text)}</div>`).join("");
    return `<div class="tiny-head"><span>${esc(state.model)}</span><span>/</span><span class="mode">${esc(state.mode==="Markdown"?"Markdown":"Chat")}</span><button class="menu-button" data-action="menu" aria-label="Menü">☰</button></div><div class="chatlog" id="chatlog">${bubbles}</div><form class="inputbar" id="chatForm"><input id="chatInput" autocomplete="off" placeholder="Nachricht schreiben …"><button class="blue-btn" aria-label="Senden">➤</button></form>${state.keyboard?keyboardMarkup():""}${menuMarkup()}`;
  }
  function keyboardMarkup(){return `<div class="keyboard-open"><div class="keyrow">${"QWERTYUIOP".split("").map(k=>`<button data-type="${k}">${k}</button>`).join("")}</div><div class="keyrow">${"ASDFGHJKL".split("").map(k=>`<button data-type="${k}">${k}</button>`).join("")}</div><div class="keyrow">${"ZXCVBNM".split("").map(k=>`<button data-type="${k}">${k}</button>`).join("")}<button data-action="backspace">⌫</button></div><div class="keyrow"><button class="wide" data-action="sym">SYM</button><button class="wide" data-action="space">SPACE</button><button class="wide" data-action="keyboard">OK</button></div></div>`;}
  function calendarPage() {
    const first=new Date(state.year,state.month,1).getDay(); const offset=(first+6)%7; const days=new Date(state.year,state.month+1,0).getDate();
    const headers=["Mo","Di","Mi","Do","Fr","Sa","So"].map(x=>`<span>${x}</span>`).join("");
    const cells=Array.from({length:offset},()=>"<span></span>").join("")+Array.from({length:days},(_,i)=>{const d=i+1,k=dayKey(state.year,state.month,d);const cls=[d===5&&state.month===9&&state.year===2026?"today":"",d===state.day?"selected":"",state.events.some(e=>e.day===k)?"has-event":""].join(" ");return `<button class="${cls}" data-day="${d}">${d}</button>`;}).join("");
    const k=dayKey(state.year,state.month,state.day); const ev=state.events.filter(e=>e.day===k); const detail=state.daySettings?.[k]||{};
    return `${title("Kalender")}<div class="content calendar-content" id="calendarContent"><div class="row"><button class="small-btn" data-action="prev-month" aria-label="Vorheriger Monat">‹</button><b>${new Date(state.year,state.month,1).toLocaleDateString("de-DE",{month:"long",year:"numeric"})}</b><button class="small-btn" data-action="next-month" aria-label="Nächster Monat">›</button></div><div class="calendar-grid">${headers}${cells}</div><div class="card calendar-detail"><div class="row"><div class="section-title">${k}</div><button class="small-btn ${detail.marked?"marked":""}" data-action="toggle-mark">${detail.marked?"★ Markiert":"☆ Markieren"}</button></div>${ev.length?ev.map(e=>`<div class="list-row">◷ ${esc(e.title)} <span class="muted">${esc(e.time||"")}</span></div>`).join(""):`<span class="muted">Noch keine Termine.</span>`}<label class="field-label" for="dayNote">Tagesnotiz</label><textarea id="dayNote" placeholder="Notiz zu diesem Tag …" rows="2">${esc(state.dayNotes?.[k]||"")}</textarea><div class="row alarm-row"><button class="small-btn ${detail.alarm?"marked":""}" data-action="toggle-alarm">${detail.alarm?"◉ Wecker an":"◯ Wecker aus"}</button><label>Uhrzeit <input id="dayAlarmTime" type="time" value="${esc(detail.time||"08:00")}"></label></div><div class="row"><button class="small-btn" data-action="save-day">Tag speichern</button><button class="small-btn" data-action="new-event">＋ Termin</button></div><small class="muted">Demo: lokal im Browser gespeichert, kein echter Wecker.</small></div></div>${menuMarkup()}`;
  }
  function notesPage() {
    const active=state.notes.find(n=>n.id===state.activeNoteId);
    if(active)return `${title("Notizen",`<button class="small-btn note-star" data-action="toggle-note-favorite" aria-label="Favorit">${state.favorites.includes(active.id)?"★":"☆"}</button>`)}<div class="content note-editor"><input id="noteTitle" class="note-title" maxlength="64" placeholder="Titel" value="${esc(active.title||"")}"><textarea id="noteBody" class="note-body" placeholder="Notiz schreiben …">${esc(active.body||"")}</textarea><div class="row"><span class="muted">Wird lokal automatisch gespeichert</span><button class="small-btn danger" data-action="delete-note">Löschen</button></div></div>${menuMarkup()}`;
    return `${title("Notizen",`<button class="small-btn notes-new" data-action="new-note">+ Neu</button>`)}<div class="content notes-list">${state.notes.length?state.notes.map((n,i)=>`<div class="card note-card"><button class="note-open" data-note="${esc(n.id)}"><b>${esc(n.title||"(ohne Titel)")}</b><span class="muted note-preview">${esc(n.body).slice(0,130)}</span></button><button class="small-btn" data-favorite="${i}">${state.favorites.includes(n.id)?"★":"☆"}</button></div>`).join(""):`<div class="card muted">Noch keine Notizen – tippe auf + Neu</div>`}</div>${menuMarkup()}`;
  }
  function terminalPage() {
    const target=state.termTarget||(state.termConnected?"Hermes · SSH (Demo)":"SSH-Ziel nicht eingerichtet");
    return `<div class="terminal-head"><span class="terminal-target">${esc(target)}</span><button class="menu-button terminal-menu-button" data-action="menu" aria-label="Terminalmenü">≡</button></div><div class="term" id="termout" style="font-size:${[12,14,16][state.termZoom||0]}px">${state.terminal.map(t=>`<div class="termline ${t.startsWith("$")?"prompt":""}">${esc(t)}</div>`).join("")}</div><form class="inputbar terminal-inputbar" id="termForm"><input id="termInput" autocomplete="off" placeholder="Befehl eingeben ..."><button class="blue-btn">&gt;</button></form>${menuMarkup()}`;
  }
  function favoritesPage(){const items=[...state.favorites.map(i=>state.notes.find(n=>n.id===i)).filter(Boolean).map(n=>`<div class="list-row">★ Notiz · ${esc(n.title)}</div>`),`<div class="list-row">★ Mesh · Heltec V3 868 <span class="pill">online</span></div>`];return `${title("Favoriten")}${content(items.join("")||`<span class="muted">Noch keine Favoriten.</span>`) }${menuMarkup()}`;}
  function genericPage(page){const data={mesh:["Meshtastic","Mesh läuft als Demo-Status. Funk wird nicht gestartet.","Heltec V3 868 · online (simuliert)","Eigener Knoten · Position 52.5253, 13.5209"],chats:["Chats","Lokale Mesh-Unterhaltungen (Beispiel)","Heltec V3 868: Position empfangen","Direktchat · Noch keine neuen Nachrichten"],alerts:["Meldungen","Keine wichtigen Meldungen.","Mesh-Verbindung: simuliert aktiv","GPS: Demo-Ortung · 7 Satelliten"],getapps:["Apps holen","Lokaler Katalog (Vorschau)","Es werden keine Apps heruntergeladen.","Installationen bleiben in der Demo."],files:["Dateien","Lokaler SD-Karten-Browser (Vorschau)","/maps · /notes · /apps","Demo-Inhalte; keine echte SD-Karte."],nodes:["Knoten","Knotenliste (simuliert)","Heltec V3 868 · Favorit","T-Deck · Position 52.5253, 13.5209"],clock:["Uhr","Stoppuhr / Timer / Wecker (Vorschau)","Keine Wecker- oder Hintergrundfunktion aktiv.","Die Timer-App heißt im Launcher Uhr."]};const [t,a,b,c]=data[page]||[page,"Demoansicht",""," "];return `${title(t)}${content(`<div class="card">${esc(a)}</div><div class="list-row">${esc(b)}</div><div class="list-row">${esc(c)}</div>`) }${menuMarkup()}`;}
  function settingsPage(){return `${title("Einstellungen")}<div class="content"><div class="section-title">Startbildschirm</div><div class="settings-row">Glas-Logos <span class="toggle ${state.glass?"on":""}" data-toggle="glass"></span></div><div class="section-title" style="margin-top:10px">Tastatur</div><div class="settings-row">T9-Wortvorschläge <span class="toggle ${state.t9?"on":""}" data-toggle="t9"></span></div><div class="list-row muted">Offline · Vorschlag antippen, um das Wort einzusetzen.</div><div class="section-title" style="margin-top:10px">Geräteschutz</div><div class="list-row">Die Geräteeinstellungen bleiben unverändert.</div></div>${menuMarkup()}`;}
  function calculatorPage(){return `${title("Rechner")}<div class="content"><div class="calc-display" id="calcDisplay">0</div><div class="calc-grid">${["7","8","9","÷","4","5","6","×","1","2","3","−","C","0","=","+"].map(x=>`<button class="${"÷×−+".includes(x)?"op":""}" data-calc="${x}">${x}</button>`).join("")}</div></div>${menuMarkup()}`;}
  function pageBody(){switch(state.page){case"launcher":return launcher();case"map":return mapPage();case"todo":return todoPage();case"transit":return transitPage();case"ollama":return chatPage();case"calendar":return calendarPage();case"notes":return notesPage();case"terminal":return terminalPage();case"favorites":return favoritesPage();case"settings":return settingsPage();case"calculator":return calculatorPage();default:return genericPage(state.page);}}
  function render(){hideSuggestions();view.innerHTML=pageBody();view.style.fontSize=[".9em","1em","1.12em"][state.zoom??1];view.classList.toggle("glass",state.glass&&state.page==="launcher");simState.textContent=`${state.page==="launcher"?"Startbildschirm":apps.find(a=>a[2]===state.page)?.[0]||state.page} · Demo aktiv`;statusbar.onclick=()=>navigate("launcher");if(state.page==="ollama")setTimeout(()=>{const l=document.getElementById("chatlog");if(l)l.scrollTop=l.scrollHeight;},0);if(state.page==="terminal")setTimeout(()=>{const l=document.getElementById("termout");if(l)l.scrollTop=l.scrollHeight;},0);}
  function mockAnswer(text){const low=text.toLowerCase();if(low.includes("hallo")||low.includes("hi"))return"Hey! Das ist eine lokale Simulator-Antwort – es wurde kein Cloud-Modell kontaktiert.";if(low.includes("markdown"))return"Wir können die Idee sauber strukturieren. Tippe /markdown für den Moduswechsel und /save, um das Ergebnis als lokale Demo-Note zu sichern.";if(low.includes("karte"))return"Die Kartenansicht lädt hier lokale Berliner OSM-Carto-Testkacheln. Mesh-Positionsdaten sind simuliert.";return`Demo-Antwort auf: „${text.slice(0,120)}“\n\nKeine Netzwerkverbindung – die echte Firmware würde hier die konfigurierte Ollama-API nutzen.`;}
  function sendChat(text){text=text.trim();if(!text)return;if(text==="/markdown"){state.mode="Markdown";toast("Markdown-Modus aktiv");}else if(text==="/kalender"){navigate("calendar");toast("Kalender-Demo geöffnet");return;}else if(text==="/save"){saveChatAsNote();render();toast("Als Demo-Notiz gespeichert");return;}else if(text==="/clear"||text==="/delete"){state.chat=[];toast("Demo-Chat gelöscht");}else{state.chat.push({role:"user",text});state.chat.push({role:"assistant",text:mockAnswer(text)});}save();render();}
  function saveChatAsNote(){const body=state.chat.map(m=>`${m.role==="user"?"Du":"Ollama"}: ${m.text}`).join("\n\n");if(!body){toast("Chat ist leer");return;}state.notes.unshift({id:crypto.randomUUID(),title:`Chat ${new Date().toLocaleDateString("de-DE")}`,body:`# Chat-Zusammenfassung (Demo)\n\n${body}`});state.mode="Chat";save();}
  function submitTerminal(cmd){cmd=cmd.trim();if(!cmd)return;state.terminal.push(`$ ${cmd}`);state.termStatus="Befehl läuft (Demo)";switch(cmd){case"help":state.terminal.push("help · pwd · ls · whoami · date · meshtastic status · clear");break;case"pwd":state.terminal.push("/home/demo");break;case"ls":state.terminal.push("notes/  maps/  agent-session/  README.md");break;case"whoami":state.terminal.push("demo-user (simuliert)");break;case"date":state.terminal.push(new Date().toString());break;case"meshtastic status":state.terminal.push("Mesh: connected (mock) · Node: Heltec V3 868");break;case"clear":state.terminal=[];break;default:state.terminal.push(`Befehl nicht in der Demo: ${cmd}`);}state.termStatus="Bereit · lokale Demo";state.terminalLog=[...state.terminal];save();render();}
  view.addEventListener("click",e=>{const b=e.target.closest('[data-action="ssh"],[data-action="read-terminal"],[data-action="clear-terminal"],[data-action="term-zoom-in"],[data-action="term-zoom-out"]');if(!b||state.page!=="terminal")return;e.preventDefault();e.stopImmediatePropagation();switch(b.dataset.action){case"ssh":state.termConnected=!state.termConnected;state.termTarget=state.termConnected?"Hermes · SSH (Demo)":"SSH target not configured";state.termStatus=state.termConnected?"SSH verbunden (simuliert)":"SSH getrennt (Demo)";state.terminal.push(state.termConnected?"[terminal] SSH verbunden (simuliert)":"[terminal] SSH getrennt (Demo)");state.terminalLog=[...state.terminal];break;case"read-terminal":state.terminal=Array.isArray(state.terminalLog)?[...state.terminalLog]:["Terminal bereit."];state.termStatus="SD-Log gelesen (Demo)";break;case"clear-terminal":state.terminal=[];state.terminalLog=[];state.termStatus="Verlauf geloescht (Demo)";break;case"term-zoom-out":state.termZoom=Math.max(0,(state.termZoom||0)-1);state.termStatus=`Zoom ${["klein","normal","gross"][state.termZoom]}`;break;case"term-zoom-in":state.termZoom=Math.min(2,(state.termZoom||0)+1);state.termStatus=`Zoom ${["klein","normal","gross"][state.termZoom]}`;break;}save();render();},true);
  view.addEventListener("click",e=>{const open=e.target.closest("[data-open]");if(open){navigate(open.dataset.open);return;}const action=e.target.closest("[data-action]");if(action){const a=action.dataset.action;switch(a){case"menu":state.menu=!state.menu;render();break;case"home":navigate("launcher");break;case"keyboard":state.keyboard=!state.keyboard;state.menu=false;render();break;case"model":{const models=["gpt-oss:120b","qwen3:latest","llama3.3:latest","deepseek-r1:latest"];state.model=models[(models.indexOf(state.model)+1)%models.length];state.menu=false;save();render();break;}case"mode":state.mode=state.mode==="Chat"?"Markdown":"Chat";state.menu=false;save();render();break;case"save-chat":saveChatAsNote();state.menu=false;render();toast("In Notes gespeichert (Demo)");break;case"delete-chat":state.chat=[];state.menu=false;save();render();toast("Demo-Chat gelöscht");break;case"open-calendar":navigate("calendar");break;case"map-style":state.mapStyle=(["OSM-Carto","Tram","S-Bahn","U-Bahn","WLAN"])[(((["OSM-Carto","Tram","S-Bahn","U-Bahn","WLAN"].indexOf(state.mapStyle||"OSM-Carto"))+1)%5)];state.menu=false;save();render();break;case"zoom-map":state.mapZoom=(state.mapZoom||16)>=17?15:(state.mapZoom||16)+1;save();render();break;case"prev-month":state.month--;if(state.month<0){state.month=11;state.year--;}save();render();break;case"next-month":state.month++;if(state.month>11){state.month=0;state.year++;}save();render();break;case"today":state.month=9;state.year=2026;state.day=5;save();render();break;case"save-day":{let k=dayKey(state.year,state.month,state.day);state.dayNotes??={};state.dayNotes[k]=document.getElementById("dayNote")?.value||"";save();toast("Tagesnotiz in Demo gespeichert");break;}case"new-event":{let name=prompt("Demo-Termin für "+dayKey(state.year,state.month,state.day));if(name){state.events.push({day:dayKey(state.year,state.month,state.day),title:name,time:"12:00"});save();render();}break;}case"new-note":{let title=prompt("Titel der Demo-Note");if(title){state.notes.unshift({id:crypto.randomUUID(),title,body:"Neue lokale Demo-Notiz.\n\nMit Doppelklick zum späteren Bearbeiten."});save();render();}break;}case"clear-terminal":state.terminal=[];save();render();break;case"ssh":state.termConnected=!state.termConnected;state.terminal.push(state.termConnected?"SSH verbunden (simuliert; kein echter Host).":"SSH Demo getrennt.");save();render();break;case"zoom":state.zoom=state.zoom===1?2:1;state.menu=false;view.style.fontSize=state.zoom===2?"1.08em":"";render();break;case"backspace":case"space":case"sym":toast("Tastatur-Demo");break;default:break;}return;}
    const day=e.target.closest("[data-day]");if(day){state.day=Number(day.dataset.day);save();render();return;}const fav=e.target.closest("[data-favorite]");if(fav){const n=state.notes[Number(fav.dataset.favorite)];if(!n)return;state.favorites=state.favorites.includes(n.id)?state.favorites.filter(x=>x!==n.id):[...state.favorites,n.id];save();render();return;}const tog=e.target.closest("[data-toggle]");if(tog){const k=tog.dataset.toggle;state[k]=!state[k];save();render();return;}const calc=e.target.closest("[data-calc]");if(calc){const d=document.getElementById("calcDisplay");if(calc.dataset.calc==="C")d.textContent="0";else if(calc.dataset.calc==="="){try{const expr=d.textContent.replaceAll("×","*").replaceAll("÷","/").replaceAll("−","-");if(/^[\d+*/(). -]+$/.test(expr))d.textContent=String(Function(`return (${expr})`)());}catch{d.textContent="Error";}}else d.textContent=d.textContent==="0"?calc.dataset.calc:d.textContent+calc.dataset.calc;return;}
    if(e.target.id==="spaceKey"){toast("SPACE · SYM-Shortcuts hier nur zur Vorschau");return;}if(e.target.id==="symKey"){e.target.classList.toggle("pressed");setTimeout(()=>e.target.classList.remove("pressed"),350);return;}if(e.target.closest(".keyboard-open [data-type]")){const b=e.target.closest("[data-type]");const input=view.querySelector("input:focus")||document.getElementById("chatInput");if(input){input.value+=b.dataset.type.toLowerCase();input.dispatchEvent(new Event("input"));}return;}
  });
  document.addEventListener("focusin",e=>{if(e.target.matches("input, textarea")){activeInput=e.target;updateSuggestions(activeInput);}});
  view.addEventListener("input",e=>{if(e.target.matches("input, textarea")){activeInput=e.target;updateSuggestions(activeInput);}});
  view.addEventListener("input",e=>{
    if(e.target.id==="noteTitle"||e.target.id==="noteBody"){
      const note=state.notes.find(n=>n.id===state.activeNoteId);
      if(note){note.title=document.getElementById("noteTitle")?.value||"";note.body=document.getElementById("noteBody")?.value||"";note.updatedAt=new Date().toISOString();save();}
    }
  });
  deviceKeyboard.addEventListener("click",e=>{const key=e.target.closest("button");if(!key||key.id==="symKey"||["SHIFT","ALT","MIC"].includes(key.textContent.trim()))return;const input=activeInput||view.querySelector("input, textarea");if(!input)return;if(key.id==="spaceKey")input.value+=" ";else if(key.textContent.trim()==="⌫")input.value=input.value.slice(0,-1);else if(key.textContent.trim()==="↵"){input.closest("form")?.requestSubmit();return;}else input.value+=key.textContent.trim().toLowerCase();input.dispatchEvent(new Event("input",{bubbles:true}));});
  view.addEventListener("click",e=>{const button=e.target.closest('[data-action="model"],[data-action="mode"],[data-action="map-style"],[data-action="zoom"],[data-action="close-menu"]');if(!button)return;e.preventDefault();e.stopImmediatePropagation();if(button.dataset.action==="model"){const models=["gpt-oss:120b","qwen3:latest","llama3.3:latest","deepseek-r1:latest"];state.model=models[(models.indexOf(state.model)+1)%models.length];}else if(button.dataset.action==="mode"){state.mode=state.mode==="Chat"?"Markdown":"Chat";}else if(button.dataset.action==="map-style"){const styles=["OSM-Carto","Tram","S-Bahn","U-Bahn","WLAN"];state.mapStyle=styles[(styles.indexOf(state.mapStyle||"OSM-Carto")+1)%styles.length];}else if(button.dataset.action==="zoom"){state.zoom=((state.zoom??1)+1)%3;}else{state.menu=false;}save();render();},true);
  view.addEventListener("click",e=>{
    const note=e.target.closest("[data-note]");
    const day=e.target.closest("[data-day]");
    const action=e.target.closest('[data-action="toggle-mark"],[data-action="toggle-alarm"],[data-action="save-day"],[data-action="new-note"],[data-action="toggle-note-favorite"],[data-action="delete-note"],[data-action="prev-month"],[data-action="next-month"],[data-action="today"],[data-action="new-event"]');
    if(!note&&!day&&!action)return;
    e.preventDefault();e.stopImmediatePropagation();
    const saveCalendarFields=()=>{
      if(state.page!=="calendar")return;
      const key=dayKey(state.year,state.month,state.day);
      state.dayNotes??={};state.daySettings??={};
      const noteField=document.getElementById("dayNote"),timeField=document.getElementById("dayAlarmTime");
      if(noteField)state.dayNotes[key]=noteField.value;
      if(timeField)state.daySettings[key]={...state.daySettings[key],time:timeField.value||"08:00"};
    };
    if(note){state.activeNoteId=note.dataset.note;render();return;}
    if(day){saveCalendarFields();state.day=Number(day.dataset.day);save();render();setTimeout(()=>document.getElementById("calendarContent")?.scrollTo({top:document.getElementById("calendarContent").scrollHeight,behavior:"smooth"}),30);return;}
    const key=dayKey(state.year,state.month,state.day);state.daySettings??={};
    switch(action.dataset.action){
      case"toggle-mark":saveCalendarFields();state.daySettings[key]={...state.daySettings[key],marked:!state.daySettings[key]?.marked};save();render();break;
      case"toggle-alarm":saveCalendarFields();state.daySettings[key]={...state.daySettings[key],alarm:!state.daySettings[key]?.alarm,time:document.getElementById("dayAlarmTime")?.value||state.daySettings[key]?.time||"08:00"};save();render();break;
      case"save-day":saveCalendarFields();save();toast("Tag in Demo gespeichert");break;
      case"new-event":{saveCalendarFields();const name=prompt("Demo-Termin für "+key);if(name){state.events.push({day:key,title:name,time:"12:00"});save();render();}break;}
      case"new-note":{const id=crypto.randomUUID();state.notes.unshift({id,title:"Neue Notiz",body:"",updatedAt:new Date().toISOString()});state.activeNoteId=id;save();render();document.getElementById("noteTitle")?.focus();break;}
      case"toggle-note-favorite":{saveActiveNote();const id=state.activeNoteId;state.favorites=state.favorites.includes(id)?state.favorites.filter(x=>x!==id):[...state.favorites,id];save();render();break;}
      case"delete-note":{const id=state.activeNoteId;state.notes=state.notes.filter(n=>n.id!==id);state.favorites=state.favorites.filter(x=>x!==id);state.activeNoteId=null;save();render();toast("Demo-Note gelöscht");break;}
      case"prev-month":saveCalendarFields();state.month--;if(state.month<0){state.month=11;state.year--;}state.day=1;save();render();break;
      case"next-month":saveCalendarFields();state.month++;if(state.month>11){state.month=0;state.year++;}state.day=1;save();render();break;
      case"today":saveCalendarFields();state.month=9;state.year=2026;state.day=5;save();render();break;
    }
  },true);
  view.addEventListener("click",e=>{const shortcut=e.target.closest('[data-action="quick-todo"],[data-action="quick-point"]');if(!shortcut||state.page!=="launcher")return;e.preventDefault();e.stopImmediatePropagation();if(shortcut.dataset.action==="quick-todo"){navigate("todo");setTimeout(()=>document.getElementById("todoInput")?.focus(),0);}else{state.mapPins??=[];state.mapPins.push({label:`Point ${state.mapPins.length+1}`,area:"map center"});save();navigate("map");toast("Point in Maps gesetzt (Demo · Kartenmitte)");}},true);
  view.addEventListener("click",e=>{const todoAction=e.target.closest("[data-todo-toggle],[data-todo-delete]");if(!todoAction||state.page!=="todo")return;e.preventDefault();e.stopImmediatePropagation();const i=Number(todoAction.dataset.todoToggle??todoAction.dataset.todoDelete);if(todoAction.hasAttribute("data-todo-toggle"))state.todos[i].done=!state.todos[i].done;else state.todos.splice(i,1);save();render();},true);
  document.addEventListener("click",e=>{const nav=e.target.closest("[data-nav]");if(!nav||state.page!=="launcher")return;e.preventDefault();e.stopImmediatePropagation();state.launcherPage=Math.max(0,Math.min(1,(state.launcherPage||0)+(nav.dataset.nav==="right"?1:-1)));save();render();},true);
  view.addEventListener("change",e=>{if(e.target.matches("[data-action=map-select]")){state.mapStyle=e.target.value;save();render();}});
  view.addEventListener("change",e=>{if(e.target.matches("[data-action=transit-select]")){state.transitPlan=e.target.value;save();render();}});
  view.addEventListener("click",e=>{
    const action=e.target.closest('[data-action="open-transit"],[data-action="transit-zoom-in"],[data-action="transit-zoom-out"],[data-action="transit-center"],[data-action="transit-osm"]');
    if(!action)return;
    e.preventDefault();e.stopImmediatePropagation();
    switch(action.dataset.action){
      case"open-transit":navigate("transit");break;
      case"transit-zoom-in":state.transitZoom=Math.min(5,Math.round(((state.transitZoom||1)+.25)*100)/100);save();render();break;
      case"transit-zoom-out":state.transitZoom=Math.max(.5,Math.round(((state.transitZoom||1)-.25)*100)/100);save();render();break;
      case"transit-center":state.transitX=0;state.transitY=0;save();render();break;
      case"transit-osm":navigate("map");break;
    }
  },true);
  view.addEventListener("pointerdown",e=>{const image=e.target.closest(".transit-map-image");if(!image||state.page!=="transit")return;transitDrag={id:e.pointerId,startX:e.clientX,startY:e.clientY,baseX:state.transitX||0,baseY:state.transitY||0,image};image.setPointerCapture(e.pointerId);});
  view.addEventListener("pointermove",e=>{if(!transitDrag||e.pointerId!==transitDrag.id)return;state.transitX=transitDrag.baseX+e.clientX-transitDrag.startX;state.transitY=transitDrag.baseY+e.clientY-transitDrag.startY;transitDrag.image.style.transform=`translate(calc(-50% + ${state.transitX}px),calc(-50% + ${state.transitY}px)) scale(${state.transitZoom||1})`;});
  const finishTransitDrag=e=>{if(!transitDrag||e.pointerId!==transitDrag.id)return;transitDrag=null;save();};
  view.addEventListener("pointerup",finishTransitDrag);view.addEventListener("pointercancel",finishTransitDrag);
  view.addEventListener("submit",e=>{if(e.target.id==="chatForm"){e.preventDefault();const i=document.getElementById("chatInput");sendChat(i.value);}if(e.target.id==="termForm"){e.preventDefault();const i=document.getElementById("termInput");submitTerminal(i.value);}if(e.target.id==="todoForm"){e.preventDefault();const input=document.getElementById("todoInput"),text=input?.value.trim();if(!text)return;state.todos??=[];state.todos.push({text,done:false});save();render();document.getElementById("todoInput")?.focus();}});
  document.querySelectorAll("[data-open]").forEach(b=>b.addEventListener("click",()=>navigate(b.dataset.open)));
  document.querySelectorAll("[data-nav]").forEach(b=>b.addEventListener("click",()=>{if(state.page==="map"){state.mapZoom=(state.mapZoom||16)+(b.dataset.nav==="right"?1:-1);state.mapZoom=Math.max(15,Math.min(17,state.mapZoom));render();}else if(state.page==="launcher"){toast("Launcher-Seite · Demo");}else{navigate("launcher");}}));
  document.getElementById("resetDemo").addEventListener("click",()=>{if(confirm("Nur lokale Demo-Daten zurücksetzen? Das T-Deck bleibt unberührt.")){localStorage.removeItem(KEY);state={...initial};render();toast("Demo zurückgesetzt");}});
  document.getElementById("clearChecks").addEventListener("click",()=>document.querySelectorAll(".checklist input").forEach(x=>x.checked=false));
  document.getElementById("exportDemo").addEventListener("click",()=>{const blob=new Blob([JSON.stringify(state,null,2)],{type:"application/json"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="tdeck-simulator-demo.json";a.click();URL.revokeObjectURL(a.href);});
  document.addEventListener("keydown",e=>{if(e.key==="Escape"){state.menu=false;state.keyboard=false;render();}if(e.key==="Home"&&e.altKey){navigate("launcher");}});
  setInterval(()=>{document.getElementById("clock").textContent=new Date().toLocaleTimeString("de-DE",{hour:"2-digit",minute:"2-digit"});},15000);
  render();
})();
